In [1]:
import numpy as np

In [9]:
l = [1, 2, 3, 4, 5]
l2 = np.array(l)    # 대부분의 경우에 사용
l3 = np.array(l, dtype = 'f')   # 옵션줘서 자료형 지정

print( type(l), type(l2) )
print( type(l[0]), type(l2[0]), type(l3[0] ))

<class 'list'> <class 'numpy.ndarray'>
<class 'int'> <class 'numpy.int64'> <class 'numpy.float32'>


In [12]:
a = np.array([[1,2,3],[4,5,6]])
print (a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [11]:
a.shape = (3, 2)
print(a.shape)
print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [15]:
# 배열의 차원의 개수 정보
a = np.arange(24) # 0부터 24개를 뽑겠다. 유사한 것이 range(24)
print(a.ndim)
print(a)
b = a.reshape(2,4,3) # a를 4행 3열 2개인 3차원의 데이터
print(b.ndim)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [19]:
x = np.empty([3,2], dtype=int)
print('empty', x)

x = np.zeros((5,), dtype="int")
print('zeros', x)

x = np.ones([2,2], dtype=int)
print('ones', x)

empty [[1 2]
 [3 4]
 [5 6]]
zeros [0 0 0 0 0]
ones [[1 1]
 [1 1]]


In [22]:
x = np.arange(10,20,2)
print (x)

[10 12 14 16 18]


In [26]:
a = np.linspace(1.0, 2.0, num = 5)
print (a)
# 시각화 할때 많이 사용. 1.0~2.0까지 숫자 5개를 뽑아라
# 끝값 포함이 기본값

x = np.linspace(10,20, 5, endpoint = False, retstep = True)
print (x) 
# endpoin를 지정해서 미포함으로 설정
# retstep은 간격이 얼마인지 계산해줌

[1.   1.25 1.5  1.75 2.  ]
(array([10., 12., 14., 16., 18.]), np.float64(2.0))


In [28]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
# Slicing
a = np.arange(10)
b = a[2:7:2] 
# [from:to:step] - 2번째(포함)에서 7번째(미포함)까지, 간격은 2로 자르기
print (b)

# Indexing
a = np.arange(10)
b = a[5] # 해당 위치에 있는 값만 가져오기
print (b)

# Slicing 2번째 부터 끝까지
a = np.arange(10)
print (a[2:])

# Slicing 처음부터 2번째 까지
a = np.arange(10)
print (a[:2])


[2 4 6]
5
[2 3 4 5 6 7 8 9]
[0 1]


In [38]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (a)
print(a.shape)
# 3행 3열로 나옴
print (a[1:])
# 2차원이라서 1개만 넣으면 행에 대한 슬라이싱만 한다.


[[1 2 3]
 [3 4 5]
 [4 5 6]]
(3, 3)
[[3 4 5]
 [4 5 6]]
[[3 4 5]]


In [39]:
# 슬라이싱 2차원 배열 열과 행을 맞춰 자르기
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0,1,2], [0,1,0]]
# 0행 0열, 1행 1열, 2행 0열
print (y)

[1 4 5]


In [44]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]])
print(x.shape, '\n', x, '\n')

z = x[1:4,1:3] #1행 ~ 4행, 1열 ~ 3열
print (z, '\n')

y = x[1:4,[1,2]]
# 인덱싱과 슬라이승, 행 슬라이싱하고 열은 1열과 2열만 가져오라는 것
print (y, '\n')

(4, 3) 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 4  5]
 [ 7  8]
 [10 11]] 

[[ 4  5]
 [ 7  8]
 [10 11]] 



In [47]:
# 불린 인덱싱

x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print(x, '\n', x>5, '\n')
print(x[x > 5])
# 5이하는 false, 5초과는 true.
# 이 경우 true만 반환한다. 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 [[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]] 

[ 6  7  8  9 10 11]


In [52]:
# missing value 찾는 방법
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(a)

print(np.isnan(a))
# nan이 있는 위치만 true

print(~np.isnan(a))
# 위 결과를 반전시켜서 T/F를 바꿈

print(a[~np.isnan(a)])
# 첫 결과를 반전시켜서 nan이 아닌 값만 반환


[nan  1.  2. nan  3.  4.  5.]
[ True False False  True False False False]
[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]


In [54]:
# 브로드캐스팅 (Broadcasting)
# 넘파이는 엘리먼트와이즈연산을한다
# 같은 열 수라면, 수직행 끼리 연산
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


In [58]:
# 브로드캐스팅 (Broadcasting) - 구조가 다를때 구조에 맞춰서 연산해줌
# 형태가 다른 배열 연산 처리
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
print(a.shape, b.shape)
print (a + b)
# a의 각 열과 b를 연산한다.
# 이때 b의 값 개수가 a열의 개수와 맞지 않으면 에러남

(4, 3) (3,)
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [60]:
# numpy.nditer (잘 안씀)

a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
print()
for x in np.nditer(a, order = 'C'):
    # c언어에서 데이터를 읽는 순서
    print (x, end=' ')
print ('\n')
for x in np.nditer(a, order = 'F'):
    # 포츠란? 언어에서 데이터를 읽는 순서
    print (x, end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

0 5 10 15 20 25 30 35 40 45 50 55 

0 20 40 5 25 45 10 30 50 15 35 55 