# 혼동행렬

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 불균형 데이터

In [ ]:
# 데이터 준비
from sklearn.datasets import load_digits
# load_digits 손글씨 숫자

digits_dataset = load_digits()
np.unique(digits_dataset['target'], return_counts=True)
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
# array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180]
# 0~9까지 보면 거의 균형 데이터 셋임

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180]))

In [ ]:
# 불균형 데이터셋 만들기
from sklearn.model_selection import train_test_split
X = digits_dataset['data']
y = digits_dataset['target']
# 이건 균형 데이터 셋 > 변형 주기
yis3 = (y == 3) 
# yis3은 불균형 데이터셋 > y== 3 T, y != 3 F 이진된다
# 이건 불린. ml전부 숫자여야해서 타입 바꾸기
yis3 = (y == 3).astype(int)
# print( np.unique(yis3, return_counts=True) ) # 테스트

X_train, X_test, y_train, y_test = train_test_split(X, yis3, stratify=yis3, random_state=42)

(array([0, 1]), array([1614,  183]))


In [ ]:
# 모델 훈련 - 3개
from sklearn.dummy import DummyClassifier   # 알고리즘으로 학습하지 않는 모델
